- hosts: localhost
  connection: local
  become: no
  gather_facts: no

  vars:
    kafka_version: 0.11.0.1

  tasks:
    - name: Download tarball
      get_url:
        url: http://ftp.yz.yamagata-u.ac.jp/pub/network/apache/kafka/{{ kafka_version }}/kafka_2.11-{{ kafka_version }}.tgz
        dest: .
        mode: 0644
        checksum: "sha256:0da77e1e542cf097d6025309bc996c10ceda394839c041934b86d8729ab574f1"

    - name: Extract the tarball
      #unarchive:
      #  src: ./kafka_2.11-{{ kafka_version }}.tgz
      #  dest: .
      shell: |
        tar xvfz ./kafka_2.11-{{ kafka_version }}.tgz

    #
    # Use ./gen-config.rb instead of here
    #
    #- template:
    #    src: ./roles/kafka/templates/server.properties
    #    dest: ./kafka_2.11-{{ kafka_version }}/config/server-{{ item }}.properties
    #  with_items: [1, 2, 3]
    #  tags:
    #    - kafka.config

