---
- name: systemctl daemon-reload
  shell: |
    /bin/systemctl daemon-reload

- name: restart kafka
  service:
    name: kafka
    state: restarted

- name: restart zookeeper
  service:
    name: zookeeper
    state: restarted
